version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 000930
      MYSQL_DATABASE: masterdb
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - game-network
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s

  redis:
    image: redis:latest
    ports:
        - "6389:6379"
    networks:
        - game-network
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s

  gameserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5284:5284"
    depends_on:
      - mysql
      - redis
    environment:
      ConnectionStrings__MysqlGameDBConnection: "Server=mysql;Database=gamedb;User=root;Password=000930;"
      ConnectionStrings__MasterDBConnection: "Server=mysql;Database=masterdb;User=root;Password=000930;"
      ConnectionStrings__RedisGameDBConnection: "redis:6379"
    networks:
      - game-network

networks:
  game-network:

volumes:
  mysql-data: